src = $(wildcard *.c)
obj = $(src:.c=.o)
CC=gcc
CFLAGS = -Wall -s -O3 -I/usr/include/freetype2 -I/mingw64/include/freetype2 -I/mingw64/include/ -D_WINDOWS -D_WIN32
LDFLAGS = -lopengl32 -lglew32 -lfreetype -lSDL2 -lm -L/mingw64/lib

%.c:
	$(CC) $(CFLAGS) -o $@

pong3d: $(obj)
	$(CC) -o $@ $^ $(LDFLAGS)

.PHONY: clean
clean:
	rm -f $(obj) pong3d

