src = $(wildcard *.c)
obj = $(src:.c=.o)

CC = gcc
CFLAGS = -Wall -s -O3 -I/mingw64/include/freetype2
LDFLAGS = -lopengl32 -lglew32 -lfreetype -lSDL2 -lm

%.c:
	$(CC) $(CFLAGS) -o $@

pong3d: $(obj)
	$(CC) -o $@ $^ $(LDFLAGS)

.PHONY: clean
clean:
	rm -f $(obj) pong3d

